apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  labels:
    tier: backend
data:
  config : |
    server {
      listen       80;

      index index.php index.html;
      error_log  /var/log/nginx/error.log;
      access_log /var/log/nginx/access.log;
      root /code/public;
      location / {
          try_files $uri $uri/ /index.php?$query_string;
      }
      location ~ \.php$ {
               try_files $uri =404;
               fastcgi_split_path_info ^(.+?\.php)(/.*)$;
               fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
               fastcgi_param ORIG_PATH_TRANSLATED $document_root$fastcgi_script_name;
               fastcgi_pass localhost:9000;
               fastcgi_buffer_size 16k;
               fastcgi_buffers 256 16k;
               fastcgi_busy_buffers_size 4064k;
               fastcgi_max_temp_file_size 0;
               fastcgi_index index.php;
               include fastcgi_params;
               fastcgi_read_timeout 600s;
        }
    }

