apiVersion: v1
kind: Service
metadata:
  name: backend-app
  labels:
    tier: backend
spec:
  selector:
    app: backend-app
    tier: backend
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
spec:
  revisionHistoryLimit: 0
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: backend-app
      tier: backend
  template:
    metadata:
      labels:
        app: backend-app
        tier: backend
    spec:
      enableServiceLinks: false
      securityContext:
        fsGroup: 1000
      terminationGracePeriodSeconds: 30
      containers:
        - image: nginx:latest
          name: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: code
              mountPath: /code
            - name: config
              mountPath: /etc/nginx/conf.d
        - image: mrhdolek/e-garage-backend:latest
          imagePullPolicy: "Always"
          imagePullSecrets:
            - name: regcred
          name: app
          ports:
            - containerPort: 9000
          resources:
            requests:
              memory: "100Mi"
              cpu: "100m"
            limits:
              memory: "200Mi"
              cpu: "200m"
          lifecycle:
            postStart:
              exec:
                command:
                  - "sh"
                  - "-c"
                  - >
                    cp /var/.env.dist ./.env &&
                    cp -R  ./ /code &&
                    cd /code &&
                    chmod -R ugo+w bootstrap/* &&
                    chmod -R ugo+w storage/* &&
                    php artisan migrate:refresh --force
          volumeMounts:
            - mountPath: /usr/local/etc/php/conf.d/zzmyphp.ini
              subPath: zzmyphp.ini
              name: php-fpm-config
            - mountPath: /usr/local/etc/php-fpm.d/zzmyphp-fpm.conf
              subPath: zzmyphp-fpm.conf
              name: php-fpm-config
            - mountPath: /var/.env.dist
              subPath: .env
              name: laravel-config
            - name: code
              mountPath: /code
      volumes:
        - name: php-fpm-config
          configMap:
            name: backend-php-fpm
        - name: laravel-config
          configMap:
            name: backend-config
        - name: code
          persistentVolumeClaim:
            claimName: code
        - name: config
          configMap:
            name: nginx-config
            items:
              - key: config
                path: site.conf
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: code
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: standard