apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    tier: backend
spec:
  selector:
    app: db
    tier: backend
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  revisionHistoryLimit: 0
  replicas: 1
  selector:
    matchLabels:
      app: db
      tier: backend
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: db
        tier: backend
    spec:
      containers:
        - name: db
          image: postgres:13
          ports:
            - containerPort: 5432
          resources:
            requests:
              memory: "100Mi"
              cpu: "100m"
            limits:
              memory: "200Mi"
              cpu: "200m"
          env:
            - name: LC_ALL
              value: C
            - name: POSTGRES_DB
              value: egarage
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_USER
              value: laravel