apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-secret
spec:
  secretName: cert-secret
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - egarage.store